### ISSUE TITLE
Create party

### ISSUE THREAD

**Issue by mayki0909** [mayki0909/PartyPlannerMobile#2]
You enter party name and then it redirect you to party details! And user MUST enter all data before doing other things. Beacuse of invites.
![image](https://user-images.githubusercontent.com/50374602/143687013-342ab85a-739c-4329-b56d-21b2fd8ecdf4.png)

![image](https://user-images.githubusercontent.com/50374602/143687024-0274cc83-1f73-4882-ab50-9184261f0a6b.png)

- [ ] You need to implement error message
- [ ] Typing text change to white
- [ ] Make it preaty, set margins...
![image](https://user-images.githubusercontent.com/50374602/145379273-39d18e92-a793-4b91-9317-1df303180953.png)

**Comment by klemen-1337** [comment]
Still need to fix dateTimePicker, maybe it works on mobile I dunno
