### ISSUE TITLE
Check for input errors, mobile styling for page: location, items needed

### ISSUE THREAD

**Issue by mayki0909** [mayki0909/PartyPlannerMobile#20]

**Comment by klemen-1337** [comment]
Raleway font problems

Location:
	- Obstoječi partyji imajo prazno lokacijo(tudi če si jo shranil) če greš archive-->location
	- Če urejaš že obstoječ party ne dela update, zato tudi ne autofilla polj
	
ItemsList:
	- Delete categorije mi crasha app
	- Konstantno javlja neke warninge, drugače dela
@mayki0909

**Comment by mayki0909** [comment]
Location:

- [x] -Obstoječi partyji imajo prazno lokacijo(tudi če si jo shranil) če greš archive-->location
- [x] Če urejaš že obstoječ party ne dela update, zato tudi ne autofilla polj

ItemsList:
- [x] Delete categorije mi crasha app
- [ ] Konstantno javlja neke warninge, drugače dela

**Comment by mayki0909** [comment]
To z warningi mi ni ratal drugo dela
